# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QLineEdit, QMessageBox
from PyQt6.QtGui import QPixmap
from PyQt6 import uic
from client import client

class Register(QtWidgets.QWidget):
    switch_window_login = QtCore.pyqtSignal()
    client = client()
    def __init__(self):
        super(Register, self).__init__()
        self.ui = uic.loadUi("Register.ui")
        self.ui.pushButton.clicked.connect(self.loginClicked)
        self.ui.pushButton_2.clicked.connect(self.registerClicked)
        self.ui.lineEdit_2.setEchoMode(QLineEdit.EchoMode.Password)
        self.ui.lineEdit_3.setEchoMode(QLineEdit.EchoMode.Password)
        pixmap = QPixmap("logo_v.png")  # 按指定路径找到图片
        self.ui.label.setPixmap(pixmap)  # 在label上显示图片
        self.ui.label.setScaledContents(True)  # 让图片自适应label大小

    def loginClicked(self):

        print("登陆")
        self.ui.close()
        self.switch_window_login.emit()

    def registerClicked(self):
        user_name = self.ui.lineEdit.text()
        password1 = self.ui.lineEdit_2.text()
        password2 = self.ui.lineEdit_3.text()
        if password2 != password1:
            QMessageBox.critical(self,' ','两次密码不相同')
            return
        else:
            print("register",user_name,password1)
            ans = self.client.register(user_name, password1)
            print(ans)
            if ans['statusCode'] == 200:

                QMessageBox.about(self,' ','注册成功')

                self.ui.close()
                self.switch_window_login.emit()
            else:
                QMessageBox.critical(self,' ',ans['message'])
